--- 
 - name: Deploy web servers
   hosts: localhost
   become: yes
   gather_facts: no
   vars:
     ansible_ssh_common_args: "-o StrictHostKeyChecking=no" 
   tasks:
   
      - name: Import deploy role
        import_role:
          name: roles/deploy
        tags: deploy

      - name: Import revert role
        import_role:
          name: roles/revert
        tags: revert
