---
# handlers file for deploy_nginx
#
    - name: Create a backup configuration file
      copy:
        src: /etc/nginx/nginx.conf
        dest: /my-web-server/data/backup_nginx.conf
        remote_src: true
